train:
  dataset:
    path: bdsaglam/musique-mini
    name: answerable
    split: train
  optimizer: bfsrs-medium

evaluation:
  dataset:
    path: bdsaglam/musique
    name: answerable
    split: validation

qa:
  model: llama-3-70b-tgi
  temperature: 0.5
  technique: cte

run: 1
