train:
  dataset:
    path: bdsaglam/musique-sweep
    name: answerable
    split: train
  optimizer: bfsrs-light
  ensemble: no

evaluation:
  dataset:
    path: bdsaglam/musique-sweep
    name: answerable
    split: validation

qa:
  model: llama-3.3-70b-tgi
  temperature: 0.7
  technique: ccot

run: 1
