train:
  dataset:
    path: bdsaglam/musique-mini
    name: answerable
    split: train
  optimizer: noop

evaluation:
  dataset:
    path: bdsaglam/musique
    name: answerable
    split: validation

qa:
  model: llama-3-70b-tgi
  temperature: 0.1
  technique: cot

run: 1
