train:
  dataset:
    path: bdsaglam/hotpotqa-distractor-mini
    name: default
    split: train
  optimizer: noop

evaluation:
  dataset:
    path: bdsaglam/hotpotqa-distractor
    name: default
    split: validation

qa:
  model: llama-3-70b-tgi
  temperature: 0.1
  technique: standard

run: 1
