train:
  dataset:
    path: bdsaglam/musique-sweep
    name: answerable
    split: train
  optimizer: miprov2-light
  ensemble: no

evaluation:
  dataset:
    path: bdsaglam/musique-sweep
    name: answerable
    split: validation

qa:
  model: llama-3.3-70b-tgi
  temperature: 0.1
  technique: multihop-decompose

run: 1
