train:
  dataset:
    path: bdsaglam/hotpotqa-distractor-mini
    name: default
    split: validation
  optimizer: noop

evaluation:
  dataset:
    path: bdsaglam/hotpotqa-distractor
    name: default
    split: train

qa:
  model: llama-3-70b-tgi
  temperature: 0.1
  technique: cot

run: 1
