train:
  dataset:
    path: bdsaglam/musique-mini
    name: answerable
    split: train
  optimizer: bfsrs-medium
  ensemble: no

evaluation:
  dataset:
    path: bdsaglam/musique
    name: answerable
    split: validation

qa:
  model: llama-3-70b-tgi
  temperature: 0.7
  technique: ccot

run: 1
