train:
  dataset:
    path: bdsaglam/musique-sweep
    name: answerable
    split: train
  optimizer: noop
  ensemble: no

evaluation:
  dataset:
    path: bdsaglam/musique-sweep
    name: answerable
    split: validation

retrieve:
  model_type: t5
  top_k: 3

qa:
  model: llama-3.3-70b-tgi
  temperature: 0.1
  technique: multihop-decompose

run: 1
